name = "Newton"
version = "0.1.0"
keywords = ["physics"]
defaultTargets = ["Newton"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev   = "v4.21.0"

[[require]]
name = "doc-gen4"
scope = "leanprover"
rev   = "v4.21.0"

[[lean_lib]]
name = "Newton"
